// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StartingPrice        float64  `protobuf:"fixed64,4,opt,name=startingPrice,proto3" json:"startingPrice,omitempty"`
	Image                string   `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	HighestBid           float64  `protobuf:"fixed64,7,opt,name=highestBid,proto3" json:"highestBid,omitempty"`
	OwnerId              int64    `protobuf:"varint,8,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	HighestBidder        int64    `protobuf:"varint,9,opt,name=highestBidder,proto3" json:"highestBidder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetStartingPrice() float64 {
	if m != nil {
		return m.StartingPrice
	}
	return 0
}

func (m *Item) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Item) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Item) GetHighestBid() float64 {
	if m != nil {
		return m.HighestBid
	}
	return 0
}

func (m *Item) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Item) GetHighestBidder() int64 {
	if m != nil {
		return m.HighestBidder
	}
	return 0
}

type CreateRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoadRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

type LoadResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (m *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(m, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

func (m *LoadResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *LoadResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FetchRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{5}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FetchResponse struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchResponse) Reset()         { *m = FetchResponse{} }
func (m *FetchResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()    {}
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{6}
}

func (m *FetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResponse.Unmarshal(m, b)
}
func (m *FetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResponse.Marshal(b, m, deterministic)
}
func (m *FetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResponse.Merge(m, src)
}
func (m *FetchResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResponse.Size(m)
}
func (m *FetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResponse proto.InternalMessageInfo

func (m *FetchResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *FetchResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type DeleteResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type UpdateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Item                 *Item    `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{9}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *UpdateRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{10}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteByUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByUserRequest) Reset()         { *m = DeleteByUserRequest{} }
func (m *DeleteByUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteByUserRequest) ProtoMessage()    {}
func (*DeleteByUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{11}
}

func (m *DeleteByUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByUserRequest.Unmarshal(m, b)
}
func (m *DeleteByUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteByUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByUserRequest.Merge(m, src)
}
func (m *DeleteByUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteByUserRequest.Size(m)
}
func (m *DeleteByUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByUserRequest proto.InternalMessageInfo

func (m *DeleteByUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteByUserResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteByUserResponse) Reset()         { *m = DeleteByUserResponse{} }
func (m *DeleteByUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteByUserResponse) ProtoMessage()    {}
func (*DeleteByUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{12}
}

func (m *DeleteByUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteByUserResponse.Unmarshal(m, b)
}
func (m *DeleteByUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteByUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteByUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteByUserResponse.Merge(m, src)
}
func (m *DeleteByUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteByUserResponse.Size(m)
}
func (m *DeleteByUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteByUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteByUserResponse proto.InternalMessageInfo

func (m *DeleteByUserResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteByUserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BidRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidRequest) Reset()         { *m = BidRequest{} }
func (m *BidRequest) String() string { return proto.CompactTextString(m) }
func (*BidRequest) ProtoMessage()    {}
func (*BidRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{13}
}

func (m *BidRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidRequest.Unmarshal(m, b)
}
func (m *BidRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidRequest.Marshal(b, m, deterministic)
}
func (m *BidRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidRequest.Merge(m, src)
}
func (m *BidRequest) XXX_Size() int {
	return xxx_messageInfo_BidRequest.Size(m)
}
func (m *BidRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BidRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BidRequest proto.InternalMessageInfo

func (m *BidRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BidRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BidRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type BidResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BidResponse) Reset()         { *m = BidResponse{} }
func (m *BidResponse) String() string { return proto.CompactTextString(m) }
func (*BidResponse) ProtoMessage()    {}
func (*BidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{14}
}

func (m *BidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BidResponse.Unmarshal(m, b)
}
func (m *BidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BidResponse.Marshal(b, m, deterministic)
}
func (m *BidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BidResponse.Merge(m, src)
}
func (m *BidResponse) XXX_Size() int {
	return xxx_messageInfo_BidResponse.Size(m)
}
func (m *BidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BidResponse proto.InternalMessageInfo

func (m *BidResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BidResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type FinishAuctionRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishAuctionRequest) Reset()         { *m = FinishAuctionRequest{} }
func (m *FinishAuctionRequest) String() string { return proto.CompactTextString(m) }
func (*FinishAuctionRequest) ProtoMessage()    {}
func (*FinishAuctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{15}
}

func (m *FinishAuctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishAuctionRequest.Unmarshal(m, b)
}
func (m *FinishAuctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishAuctionRequest.Marshal(b, m, deterministic)
}
func (m *FinishAuctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishAuctionRequest.Merge(m, src)
}
func (m *FinishAuctionRequest) XXX_Size() int {
	return xxx_messageInfo_FinishAuctionRequest.Size(m)
}
func (m *FinishAuctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishAuctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishAuctionRequest proto.InternalMessageInfo

func (m *FinishAuctionRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FinishAuctionRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type FinishAuctionResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishAuctionResponse) Reset()         { *m = FinishAuctionResponse{} }
func (m *FinishAuctionResponse) String() string { return proto.CompactTextString(m) }
func (*FinishAuctionResponse) ProtoMessage()    {}
func (*FinishAuctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{16}
}

func (m *FinishAuctionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishAuctionResponse.Unmarshal(m, b)
}
func (m *FinishAuctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishAuctionResponse.Marshal(b, m, deterministic)
}
func (m *FinishAuctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishAuctionResponse.Merge(m, src)
}
func (m *FinishAuctionResponse) XXX_Size() int {
	return xxx_messageInfo_FinishAuctionResponse.Size(m)
}
func (m *FinishAuctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishAuctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinishAuctionResponse proto.InternalMessageInfo

func (m *FinishAuctionResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FinishAuctionResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "item.Item")
	proto.RegisterType((*CreateRequest)(nil), "item.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "item.CreateResponse")
	proto.RegisterType((*LoadRequest)(nil), "item.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "item.LoadResponse")
	proto.RegisterType((*FetchRequest)(nil), "item.FetchRequest")
	proto.RegisterType((*FetchResponse)(nil), "item.FetchResponse")
	proto.RegisterType((*DeleteRequest)(nil), "item.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "item.DeleteResponse")
	proto.RegisterType((*UpdateRequest)(nil), "item.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "item.UpdateResponse")
	proto.RegisterType((*DeleteByUserRequest)(nil), "item.DeleteByUserRequest")
	proto.RegisterType((*DeleteByUserResponse)(nil), "item.DeleteByUserResponse")
	proto.RegisterType((*BidRequest)(nil), "item.BidRequest")
	proto.RegisterType((*BidResponse)(nil), "item.BidResponse")
	proto.RegisterType((*FinishAuctionRequest)(nil), "item.FinishAuctionRequest")
	proto.RegisterType((*FinishAuctionResponse)(nil), "item.FinishAuctionResponse")
}

func init() {
	proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df)
}

var fileDescriptor_6007f868cf6553df = []byte{
	// 554 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x3f, 0xe2, 0xd2, 0x71, 0x5d, 0xd1, 0x8d, 0x89, 0x56, 0x46, 0x8a, 0x22, 0x8b, 0x43,
	0x0e, 0x50, 0x20, 0xa8, 0x07, 0x84, 0x84, 0x20, 0xa4, 0x95, 0x8a, 0x7a, 0x40, 0x46, 0x3d, 0xc0,
	0xcd, 0x8d, 0x57, 0xc9, 0x4a, 0xf8, 0x83, 0xdd, 0x35, 0x88, 0x1b, 0x3f, 0x94, 0x1f, 0x83, 0xbc,
	0xeb, 0x4d, 0xbc, 0x51, 0x23, 0x84, 0x7b, 0xf3, 0xbc, 0xd9, 0x99, 0x79, 0xfb, 0x66, 0x66, 0x0d,
	0x40, 0x05, 0xc9, 0xcf, 0x2a, 0x56, 0x8a, 0x12, 0xb9, 0xcd, 0x77, 0xfc, 0xdb, 0x06, 0xf7, 0x4a,
	0x90, 0x1c, 0x9d, 0x80, 0x4d, 0x33, 0x6c, 0x4d, 0xac, 0xa9, 0x93, 0xd8, 0x34, 0x43, 0x08, 0xdc,
	0x22, 0xcd, 0x09, 0xb6, 0x27, 0xd6, 0xf4, 0x28, 0x91, 0xdf, 0x68, 0x02, 0x7e, 0x46, 0xf8, 0x92,
	0xd1, 0x4a, 0xd0, 0xb2, 0xc0, 0x8e, 0x74, 0x75, 0x21, 0xf4, 0x04, 0x02, 0x2e, 0x52, 0x26, 0x68,
	0xb1, 0xfa, 0xc4, 0xe8, 0x92, 0x60, 0x77, 0x62, 0x4d, 0xad, 0xc4, 0x04, 0x51, 0x08, 0x03, 0x9a,
	0xa7, 0x2b, 0x82, 0x07, 0x32, 0x83, 0x32, 0xd0, 0x08, 0x3c, 0x2e, 0x52, 0x51, 0x73, 0xec, 0x49,
	0xb8, 0xb5, 0xd0, 0x18, 0x60, 0x4d, 0x57, 0x6b, 0xc2, 0xc5, 0x9c, 0x66, 0xf8, 0x50, 0x26, 0xec,
	0x20, 0x08, 0xc3, 0x61, 0xf9, 0xb3, 0x20, 0xec, 0x2a, 0xc3, 0x0f, 0x24, 0x7d, 0x6d, 0x36, 0x6c,
	0xb6, 0xe7, 0x32, 0xc2, 0xf0, 0x91, 0xf4, 0x9b, 0x60, 0xfc, 0x1c, 0x82, 0x0f, 0x8c, 0xa4, 0x82,
	0x24, 0xe4, 0x7b, 0x4d, 0xb8, 0x40, 0x63, 0x90, 0xda, 0x48, 0x31, 0xfc, 0x19, 0x9c, 0x49, 0xd1,
	0x1a, 0x91, 0x12, 0xa5, 0xd9, 0x5b, 0x38, 0xd1, 0x01, 0xbc, 0x2a, 0x0b, 0xde, 0xa5, 0xae, 0x04,
	0xd4, 0xd4, 0x43, 0x18, 0x10, 0xc6, 0x4a, 0xd6, 0xaa, 0xa8, 0x8c, 0x38, 0x00, 0xff, 0xba, 0x4c,
	0xb3, 0xb6, 0x5c, 0xbc, 0x80, 0x63, 0x65, 0xb6, 0xc9, 0xfe, 0x51, 0x7e, 0x4f, 0xd2, 0x31, 0x1c,
	0x5f, 0x12, 0xb1, 0x5c, 0xeb, 0x4b, 0xec, 0xf4, 0x33, 0xbe, 0x80, 0xa0, 0xf5, 0xdf, 0xab, 0xcc,
	0x6b, 0x08, 0x16, 0xe4, 0x1b, 0xd9, 0x8a, 0xb5, 0x3b, 0x37, 0x9d, 0x6e, 0xd8, 0x46, 0x37, 0x1a,
	0xd9, 0x74, 0x68, 0x2f, 0xd9, 0xbe, 0x40, 0x70, 0x53, 0x65, 0x69, 0x8f, 0xd2, 0x9b, 0xbb, 0x3a,
	0xfb, 0x3b, 0xaa, 0x53, 0xf7, 0xa2, 0xf6, 0x0c, 0x86, 0xea, 0x6a, 0xf3, 0x5f, 0x37, 0x9c, 0x30,
	0x4d, 0x70, 0x04, 0x5e, 0xcd, 0x25, 0x1f, 0x4b, 0x4d, 0xb4, 0xb2, 0xe2, 0x05, 0x84, 0xe6, 0xf1,
	0x5e, 0x45, 0xaf, 0x01, 0xe6, 0x34, 0xdb, 0x27, 0xc6, 0x08, 0xbc, 0x34, 0x2f, 0xeb, 0x42, 0xc8,
	0x20, 0x2b, 0x69, 0xad, 0x0e, 0x27, 0x47, 0xd5, 0x68, 0x39, 0xbd, 0x01, 0x5f, 0x66, 0xeb, 0x45,
	0xe5, 0x1d, 0x84, 0x97, 0xb4, 0xa0, 0x7c, 0xfd, 0xbe, 0x5e, 0x36, 0xef, 0xc0, 0xff, 0x0f, 0xc7,
	0x05, 0x3c, 0xda, 0xc9, 0xd0, 0x87, 0xc8, 0xec, 0x8f, 0x0d, 0x7e, 0xd3, 0xd7, 0xcf, 0x84, 0xfd,
	0x68, 0x5e, 0x9a, 0x73, 0xf0, 0xd4, 0xaa, 0xa2, 0xa1, 0x6a, 0xba, 0xb1, 0xe9, 0x51, 0x68, 0x82,
	0xaa, 0x64, 0x7c, 0x80, 0x5e, 0x82, 0xdb, 0xac, 0x24, 0x3a, 0x55, 0xfe, 0xce, 0xb6, 0x46, 0xa8,
	0x0b, 0xe9, 0x80, 0x17, 0x16, 0x9a, 0xc1, 0x40, 0xee, 0x17, 0x6a, 0x0f, 0x74, 0x97, 0x31, 0x1a,
	0x1a, 0xd8, 0xa6, 0xcc, 0x39, 0x78, 0x6a, 0x0e, 0x34, 0x3b, 0x63, 0xb5, 0x34, 0x3b, 0x73, 0x69,
	0xe2, 0x03, 0xf4, 0x14, 0x9c, 0xe6, 0xdd, 0x7b, 0xa8, 0xdc, 0xdb, 0x19, 0x88, 0x4e, 0x3b, 0xc8,
	0xe6, 0xf4, 0x47, 0x08, 0x0c, 0x65, 0x51, 0xd4, 0x92, 0xb9, 0xa3, 0x61, 0xd1, 0xe3, 0x3b, 0x7d,
	0x3a, 0xd7, 0xdc, 0xfd, 0x6a, 0x57, 0xb7, 0xb7, 0x9e, 0xfc, 0x81, 0xbc, 0xfa, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x10, 0x26, 0xec, 0xe9, 0x4e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (ItemService_LoadClient, error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error)
	FinishAuction(ctx context.Context, in *FinishAuctionRequest, opts ...grpc.CallOption) (*FinishAuctionResponse, error)
}

type itemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewItemServiceClient(cc grpc.ClientConnInterface) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/item.ItemService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (ItemService_LoadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ItemService_serviceDesc.Streams[0], "/item.ItemService/Load", opts...)
	if err != nil {
		return nil, err
	}
	x := &itemServiceLoadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ItemService_LoadClient interface {
	Recv() (*LoadResponse, error)
	grpc.ClientStream
}

type itemServiceLoadClient struct {
	grpc.ClientStream
}

func (x *itemServiceLoadClient) Recv() (*LoadResponse, error) {
	m := new(LoadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *itemServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, "/item.ItemService/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/item.ItemService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) Bid(ctx context.Context, in *BidRequest, opts ...grpc.CallOption) (*BidResponse, error) {
	out := new(BidResponse)
	err := c.cc.Invoke(ctx, "/item.ItemService/Bid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) FinishAuction(ctx context.Context, in *FinishAuctionRequest, opts ...grpc.CallOption) (*FinishAuctionResponse, error) {
	out := new(FinishAuctionResponse)
	err := c.cc.Invoke(ctx, "/item.ItemService/FinishAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Load(*LoadRequest, ItemService_LoadServer) error
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Bid(context.Context, *BidRequest) (*BidResponse, error)
	FinishAuction(context.Context, *FinishAuctionRequest) (*FinishAuctionResponse, error)
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedItemServiceServer) Load(req *LoadRequest, srv ItemService_LoadServer) error {
	return status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedItemServiceServer) Fetch(ctx context.Context, req *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (*UnimplementedItemServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedItemServiceServer) Bid(ctx context.Context, req *BidRequest) (*BidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bid not implemented")
}
func (*UnimplementedItemServiceServer) FinishAuction(ctx context.Context, req *FinishAuctionRequest) (*FinishAuctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishAuction not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Load_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ItemServiceServer).Load(m, &itemServiceLoadServer{stream})
}

type ItemService_LoadServer interface {
	Send(*LoadResponse) error
	grpc.ServerStream
}

type itemServiceLoadServer struct {
	grpc.ServerStream
}

func (x *itemServiceLoadServer) Send(m *LoadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ItemService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_Bid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).Bid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/Bid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).Bid(ctx, req.(*BidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_FinishAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).FinishAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/item.ItemService/FinishAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).FinishAuction(ctx, req.(*FinishAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "item.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ItemService_Create_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _ItemService_Fetch_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ItemService_Delete_Handler,
		},
		{
			MethodName: "Bid",
			Handler:    _ItemService_Bid_Handler,
		},
		{
			MethodName: "FinishAuction",
			Handler:    _ItemService_FinishAuction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Load",
			Handler:       _ItemService_Load_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "item.proto",
}
