// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RaiseReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RaiseReq) Reset()         { *m = RaiseReq{} }
func (m *RaiseReq) String() string { return proto.CompactTextString(m) }
func (*RaiseReq) ProtoMessage()    {}
func (*RaiseReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{0}
}

func (m *RaiseReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaiseReq.Unmarshal(m, b)
}
func (m *RaiseReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaiseReq.Marshal(b, m, deterministic)
}
func (m *RaiseReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaiseReq.Merge(m, src)
}
func (m *RaiseReq) XXX_Size() int {
	return xxx_messageInfo_RaiseReq.Size(m)
}
func (m *RaiseReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RaiseReq.DiscardUnknown(m)
}

var xxx_messageInfo_RaiseReq proto.InternalMessageInfo

func (m *RaiseReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RaiseReq) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *RaiseReq) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RaiseReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Transaction struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Transaction) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CreateRequest struct {
	RaiseReq             *RaiseReq `protobuf:"bytes,1,opt,name=raiseReq,proto3" json:"raiseReq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetRaiseReq() *RaiseReq {
	if m != nil {
		return m.RaiseReq
	}
	return nil
}

type CreateResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoadTransactionsRequest struct {
	OwnerId              int64    `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadTransactionsRequest) Reset()         { *m = LoadTransactionsRequest{} }
func (m *LoadTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*LoadTransactionsRequest) ProtoMessage()    {}
func (*LoadTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{4}
}

func (m *LoadTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadTransactionsRequest.Unmarshal(m, b)
}
func (m *LoadTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *LoadTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadTransactionsRequest.Merge(m, src)
}
func (m *LoadTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_LoadTransactionsRequest.Size(m)
}
func (m *LoadTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadTransactionsRequest proto.InternalMessageInfo

func (m *LoadTransactionsRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type LoadTransactionsResponse struct {
	Transaction          *Transaction `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Error                string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoadTransactionsResponse) Reset()         { *m = LoadTransactionsResponse{} }
func (m *LoadTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*LoadTransactionsResponse) ProtoMessage()    {}
func (*LoadTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{5}
}

func (m *LoadTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadTransactionsResponse.Unmarshal(m, b)
}
func (m *LoadTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *LoadTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadTransactionsResponse.Merge(m, src)
}
func (m *LoadTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_LoadTransactionsResponse.Size(m)
}
func (m *LoadTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadTransactionsResponse proto.InternalMessageInfo

func (m *LoadTransactionsResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *LoadTransactionsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoadRaiseReqsRequest struct {
	OwnerId              int64    `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRaiseReqsRequest) Reset()         { *m = LoadRaiseReqsRequest{} }
func (m *LoadRaiseReqsRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRaiseReqsRequest) ProtoMessage()    {}
func (*LoadRaiseReqsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{6}
}

func (m *LoadRaiseReqsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRaiseReqsRequest.Unmarshal(m, b)
}
func (m *LoadRaiseReqsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRaiseReqsRequest.Marshal(b, m, deterministic)
}
func (m *LoadRaiseReqsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRaiseReqsRequest.Merge(m, src)
}
func (m *LoadRaiseReqsRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRaiseReqsRequest.Size(m)
}
func (m *LoadRaiseReqsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRaiseReqsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRaiseReqsRequest proto.InternalMessageInfo

func (m *LoadRaiseReqsRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type LoadRaiseReqsResponse struct {
	RaiseReq             *RaiseReq `protobuf:"bytes,1,opt,name=RaiseReq,proto3" json:"RaiseReq,omitempty"`
	Error                string    `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoadRaiseReqsResponse) Reset()         { *m = LoadRaiseReqsResponse{} }
func (m *LoadRaiseReqsResponse) String() string { return proto.CompactTextString(m) }
func (*LoadRaiseReqsResponse) ProtoMessage()    {}
func (*LoadRaiseReqsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{7}
}

func (m *LoadRaiseReqsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRaiseReqsResponse.Unmarshal(m, b)
}
func (m *LoadRaiseReqsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRaiseReqsResponse.Marshal(b, m, deterministic)
}
func (m *LoadRaiseReqsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRaiseReqsResponse.Merge(m, src)
}
func (m *LoadRaiseReqsResponse) XXX_Size() int {
	return xxx_messageInfo_LoadRaiseReqsResponse.Size(m)
}
func (m *LoadRaiseReqsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRaiseReqsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRaiseReqsResponse proto.InternalMessageInfo

func (m *LoadRaiseReqsResponse) GetRaiseReq() *RaiseReq {
	if m != nil {
		return m.RaiseReq
	}
	return nil
}

func (m *LoadRaiseReqsResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId              int64    `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeleteRequest) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

type DeleteResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ChangeStatusRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatusRequest) Reset()         { *m = ChangeStatusRequest{} }
func (m *ChangeStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusRequest) ProtoMessage()    {}
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{10}
}

func (m *ChangeStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusRequest.Unmarshal(m, b)
}
func (m *ChangeStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusRequest.Marshal(b, m, deterministic)
}
func (m *ChangeStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusRequest.Merge(m, src)
}
func (m *ChangeStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusRequest.Size(m)
}
func (m *ChangeStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusRequest proto.InternalMessageInfo

func (m *ChangeStatusRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChangeStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ChangeStatusResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatusResponse) Reset()         { *m = ChangeStatusResponse{} }
func (m *ChangeStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeStatusResponse) ProtoMessage()    {}
func (*ChangeStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b88fd140af4deb6f, []int{11}
}

func (m *ChangeStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatusResponse.Unmarshal(m, b)
}
func (m *ChangeStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatusResponse.Marshal(b, m, deterministic)
}
func (m *ChangeStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatusResponse.Merge(m, src)
}
func (m *ChangeStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeStatusResponse.Size(m)
}
func (m *ChangeStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatusResponse proto.InternalMessageInfo

func (m *ChangeStatusResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ChangeStatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RaiseReq)(nil), "wallet.RaiseReq")
	proto.RegisterType((*Transaction)(nil), "wallet.Transaction")
	proto.RegisterType((*CreateRequest)(nil), "wallet.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "wallet.CreateResponse")
	proto.RegisterType((*LoadTransactionsRequest)(nil), "wallet.LoadTransactionsRequest")
	proto.RegisterType((*LoadTransactionsResponse)(nil), "wallet.LoadTransactionsResponse")
	proto.RegisterType((*LoadRaiseReqsRequest)(nil), "wallet.LoadRaiseReqsRequest")
	proto.RegisterType((*LoadRaiseReqsResponse)(nil), "wallet.LoadRaiseReqsResponse")
	proto.RegisterType((*DeleteRequest)(nil), "wallet.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "wallet.DeleteResponse")
	proto.RegisterType((*ChangeStatusRequest)(nil), "wallet.ChangeStatusRequest")
	proto.RegisterType((*ChangeStatusResponse)(nil), "wallet.ChangeStatusResponse")
}

func init() {
	proto.RegisterFile("wallet.proto", fileDescriptor_b88fd140af4deb6f)
}

var fileDescriptor_b88fd140af4deb6f = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x6d, 0xb2, 0xdb, 0x74, 0x77, 0xd8, 0xac, 0x90, 0xf9, 0x68, 0x94, 0x52, 0x35, 0xca, 0x89,
	0x03, 0x42, 0x08, 0xd4, 0x03, 0x07, 0x7a, 0x28, 0x5c, 0xaa, 0x56, 0x6a, 0x65, 0x2a, 0x55, 0x6d,
	0x4f, 0x86, 0x58, 0x34, 0x12, 0x8d, 0xa9, 0x6d, 0xca, 0x1f, 0xec, 0x0f, 0xab, 0x92, 0xd8, 0xc4,
	0x09, 0x44, 0x42, 0xec, 0x71, 0xc6, 0xf3, 0x66, 0xde, 0x9b, 0x79, 0x32, 0x3c, 0x1c, 0xc8, 0x76,
	0x4b, 0xe5, 0x70, 0xc7, 0x99, 0x64, 0xc8, 0xc9, 0xa3, 0x30, 0x82, 0x3b, 0x4c, 0x62, 0x41, 0x31,
	0xfd, 0x83, 0x1e, 0xc1, 0x8e, 0x23, 0xcf, 0x0a, 0xac, 0xfe, 0x0d, 0xb6, 0xe3, 0x08, 0x79, 0xf0,
	0x82, 0x1d, 0x12, 0xca, 0x3f, 0x44, 0x9e, 0x9d, 0x25, 0x75, 0x88, 0xba, 0xe0, 0x90, 0xdf, 0x6c,
	0x9f, 0x48, 0xef, 0x26, 0xb0, 0xfa, 0x16, 0x56, 0x51, 0x9a, 0x17, 0x92, 0xc8, 0xbd, 0xf0, 0x6e,
	0x03, 0xab, 0x7f, 0x8f, 0x55, 0x14, 0x7e, 0x86, 0xc6, 0x57, 0x4e, 0x12, 0x41, 0xd6, 0x32, 0x66,
	0xc9, 0xd3, 0x07, 0x85, 0x33, 0x70, 0xe7, 0x9c, 0x12, 0x99, 0xf2, 0xde, 0x53, 0x21, 0xd1, 0x00,
	0xee, 0xb8, 0xd2, 0x91, 0x35, 0x6e, 0x8c, 0x9b, 0x43, 0x25, 0x58, 0xeb, 0xc3, 0xc7, 0x8a, 0xf0,
	0x1d, 0x3c, 0x6a, 0xb8, 0xd8, 0xb1, 0x44, 0x50, 0x83, 0x79, 0x4e, 0x4b, 0x45, 0xa8, 0x0d, 0xcf,
	0x29, 0xe7, 0x8c, 0x67, 0xc4, 0xee, 0x71, 0x1e, 0x84, 0x13, 0x78, 0xf9, 0x89, 0x91, 0xc8, 0xd0,
	0x24, 0x34, 0x11, 0x43, 0x8b, 0x55, 0xd2, 0x12, 0x6e, 0xc0, 0x3b, 0x05, 0xa9, 0xf1, 0x6f, 0xa1,
	0x21, 0x8b, 0xbc, 0x52, 0xd0, 0xd2, 0x0a, 0x0c, 0x08, 0x36, 0xeb, 0x6a, 0xd8, 0x8d, 0xa0, 0x9d,
	0x0e, 0xd2, 0xba, 0x2f, 0xa0, 0xf6, 0x13, 0x3a, 0x15, 0x84, 0xe2, 0x35, 0x28, 0xec, 0x51, 0xbf,
	0xd6, 0xa3, 0x81, 0xce, 0xd3, 0x99, 0x82, 0xbb, 0xa0, 0x5b, 0x5a, 0xdc, 0xea, 0xe2, 0xf3, 0xa7,
	0x77, 0xd2, 0xd0, 0xab, 0xee, 0x34, 0x83, 0xd6, 0xfc, 0x17, 0x49, 0x36, 0x74, 0x99, 0x55, 0xd5,
	0x11, 0x28, 0x9a, 0xda, 0x25, 0xdb, 0x2e, 0xa0, 0x5d, 0x86, 0x5f, 0x43, 0x62, 0xfc, 0xcf, 0x06,
	0xf7, 0x5b, 0xb6, 0xb3, 0x25, 0xe5, 0x7f, 0xe3, 0x35, 0x45, 0x53, 0x70, 0x72, 0xfb, 0xa1, 0x8e,
	0xde, 0x66, 0xc9, 0xcd, 0x7e, 0xb7, 0x9a, 0xce, 0x07, 0x87, 0xcf, 0xd0, 0x77, 0x68, 0x56, 0x4d,
	0x84, 0xde, 0xe8, 0xea, 0x1a, 0x4f, 0xfa, 0x41, 0x7d, 0x81, 0x6e, 0x3c, 0xb2, 0xd0, 0x17, 0x70,
	0x4b, 0x26, 0x40, 0x3d, 0x13, 0x56, 0x75, 0x93, 0xff, 0xba, 0xe6, 0xd5, 0xe8, 0xf8, 0x11, 0x1e,
	0xcc, 0xfd, 0xa1, 0x57, 0x47, 0x59, 0xa7, 0x47, 0xf1, 0x7b, 0xe7, 0x1f, 0x75, 0xbb, 0xf7, 0xb7,
	0x3f, 0xec, 0xdd, 0x6a, 0xe5, 0x64, 0xdf, 0xd7, 0xe4, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d,
	0x98, 0x4a, 0xd3, 0xce, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	LoadTransactions(ctx context.Context, in *LoadTransactionsRequest, opts ...grpc.CallOption) (WalletService_LoadTransactionsClient, error)
	LoadRaiseReqs(ctx context.Context, in *LoadRaiseReqsRequest, opts ...grpc.CallOption) (WalletService_LoadRaiseReqsClient, error)
	ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/wallet.WalletService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) LoadTransactions(ctx context.Context, in *LoadTransactionsRequest, opts ...grpc.CallOption) (WalletService_LoadTransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WalletService_serviceDesc.Streams[0], "/wallet.WalletService/LoadTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &walletServiceLoadTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WalletService_LoadTransactionsClient interface {
	Recv() (*LoadTransactionsResponse, error)
	grpc.ClientStream
}

type walletServiceLoadTransactionsClient struct {
	grpc.ClientStream
}

func (x *walletServiceLoadTransactionsClient) Recv() (*LoadTransactionsResponse, error) {
	m := new(LoadTransactionsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *walletServiceClient) LoadRaiseReqs(ctx context.Context, in *LoadRaiseReqsRequest, opts ...grpc.CallOption) (WalletService_LoadRaiseReqsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WalletService_serviceDesc.Streams[1], "/wallet.WalletService/LoadRaiseReqs", opts...)
	if err != nil {
		return nil, err
	}
	x := &walletServiceLoadRaiseReqsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WalletService_LoadRaiseReqsClient interface {
	Recv() (*LoadRaiseReqsResponse, error)
	grpc.ClientStream
}

type walletServiceLoadRaiseReqsClient struct {
	grpc.ClientStream
}

func (x *walletServiceLoadRaiseReqsClient) Recv() (*LoadRaiseReqsResponse, error) {
	m := new(LoadRaiseReqsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *walletServiceClient) ChangeStatus(ctx context.Context, in *ChangeStatusRequest, opts ...grpc.CallOption) (*ChangeStatusResponse, error) {
	out := new(ChangeStatusResponse)
	err := c.cc.Invoke(ctx, "/wallet.WalletService/ChangeStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
type WalletServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	LoadTransactions(*LoadTransactionsRequest, WalletService_LoadTransactionsServer) error
	LoadRaiseReqs(*LoadRaiseReqsRequest, WalletService_LoadRaiseReqsServer) error
	ChangeStatus(context.Context, *ChangeStatusRequest) (*ChangeStatusResponse, error)
}

// UnimplementedWalletServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (*UnimplementedWalletServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedWalletServiceServer) LoadTransactions(req *LoadTransactionsRequest, srv WalletService_LoadTransactionsServer) error {
	return status.Errorf(codes.Unimplemented, "method LoadTransactions not implemented")
}
func (*UnimplementedWalletServiceServer) LoadRaiseReqs(req *LoadRaiseReqsRequest, srv WalletService_LoadRaiseReqsServer) error {
	return status.Errorf(codes.Unimplemented, "method LoadRaiseReqs not implemented")
}
func (*UnimplementedWalletServiceServer) ChangeStatus(ctx context.Context, req *ChangeStatusRequest) (*ChangeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeStatus not implemented")
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.WalletService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_LoadTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoadTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServiceServer).LoadTransactions(m, &walletServiceLoadTransactionsServer{stream})
}

type WalletService_LoadTransactionsServer interface {
	Send(*LoadTransactionsResponse) error
	grpc.ServerStream
}

type walletServiceLoadTransactionsServer struct {
	grpc.ServerStream
}

func (x *walletServiceLoadTransactionsServer) Send(m *LoadTransactionsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WalletService_LoadRaiseReqs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoadRaiseReqsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServiceServer).LoadRaiseReqs(m, &walletServiceLoadRaiseReqsServer{stream})
}

type WalletService_LoadRaiseReqsServer interface {
	Send(*LoadRaiseReqsResponse) error
	grpc.ServerStream
}

type walletServiceLoadRaiseReqsServer struct {
	grpc.ServerStream
}

func (x *walletServiceLoadRaiseReqsServer) Send(m *LoadRaiseReqsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _WalletService_ChangeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ChangeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.WalletService/ChangeStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ChangeStatus(ctx, req.(*ChangeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _WalletService_Create_Handler,
		},
		{
			MethodName: "ChangeStatus",
			Handler:    _WalletService_ChangeStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LoadTransactions",
			Handler:       _WalletService_LoadTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LoadRaiseReqs",
			Handler:       _WalletService_LoadRaiseReqs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wallet.proto",
}
